# Generated by Django 3.1.7 on 2021-04-06 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pollApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to=settings.AUTH_USER_MODEL),
        ),
    ]
